basePath: /api
definitions:
  app.VErr:
    properties:
      field:
        type: string
      message:
        type: string
      value:
        type: string
    type: object
  app.ValidationError:
    properties:
      errors:
        items:
          $ref: '#/definitions/app.VErr'
        type: array
      message:
        type: string
    type: object
  auth.LoginGoogleReq:
    properties:
      redirect_url:
        example: http://localhost:3000/redirect/google
        type: string
    type: object
  auth.LoginGoogleRes:
    properties:
      oauth_url:
        type: string
      state:
        type: string
    type: object
host: localhost:8000
info:
  contact: {}
  description: This is the core server to manage user accounts and contacts in
  termsOfService: http://swagger.io/terms/
  title: GoChat API documentation
  version: 1.0.0
paths:
  /auth/login/google:
    post:
      parameters:
      - description: login google request
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/auth.LoginGoogleReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/auth.LoginGoogleRes'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/app.ValidationError'
      summary: Create google oauth redirect
      tags:
      - auth
  /auth/temp:
    get:
      description: check for server connection
      produces:
      - application/json
      responses:
        "200":
          description: OK
      summary: Temporary Handler
      tags:
      - auth
swagger: "2.0"
